# Generated by Django 5.0.2 on 2024-02-26 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_delete_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
